mailhub-frontend:
    image: ghcr.io/labsativai/mailhub-frontend:latest
    container_name: mailhub-frontend
    restart: unless-stopped
    depends_on:
      - mailhub-backend
    volumes:
      - /root/mailhub-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ativaai